# Run docker-compose build
# Run docker-compose up
# Visit http://localhost
# Live long and prosper

version: '3.7'

services:

  nginx:
    container_name: behemoth-angular-frontend
    image: behemoth-angular-frontend
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - node
    networks:
      - app-network

  node:
    container_name: behemoth-service-node
    image: behemoth-service-node
    build:
      context: .
      dockerfile: .docker/node.dockerfile
    environment:
      - NODE_ENV=production
      - CONTAINER=true
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge